services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spice_wallet_api
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"